/**
 * IconRegistry — singleton that maps every required icon key to its
 * React-Native-SVG component, and validates at module-load time that
 * no key is absent.  If a key is missing a MissingIconError is thrown
 * immediately, which the app-root ErrorBoundary catches and renders as
 * a startup error screen (Req 1.4).
 */

import React from 'react';
import { SvgProps } from 'react-native-svg';

// ─── Individual SVG component imports ───────────────────────────────────────
// Each file is a React component generated by @svgr/native (or equivalent).
// For the Expo / Metro bundler we import the raw .svg files via the
// metro-transform-inline-svg / expo SVG transformer.
//
// Because the standard Expo SVG transformer wraps each .svg as a React
// component that accepts SvgProps, we import them with a typed assertion.

import HomeSvg from '../../assets/icons/home.svg';
import SettingsSvg from '../../assets/icons/settings.svg';
import ProfileSvg from '../../assets/icons/profile.svg';
import LogoutSvg from '../../assets/icons/logout.svg';
import LanguageSvg from '../../assets/icons/language.svg';
import ThemeSvg from '../../assets/icons/theme.svg';
import JobSeekerSvg from '../../assets/icons/job_seeker.svg';
import RecruiterSvg from '../../assets/icons/recruiter.svg';
import ApplySvg from '../../assets/icons/apply.svg';
import DeactivateSvg from '../../assets/icons/deactivate.svg';
import DeleteSvg from '../../assets/icons/delete.svg';
import PaymentSvg from '../../assets/icons/payment.svg';
import ReceiptSvg from '../../assets/icons/receipt.svg';
import SubscriptionSvg from '../../assets/icons/subscription.svg';
import UpiSvg from '../../assets/icons/upi.svg';
import PhoneSvg from '../../assets/icons/phone.svg';
import OtpSvg from '../../assets/icons/otp.svg';
import LockSvg from '../../assets/icons/lock.svg';
import SearchSvg from '../../assets/icons/search.svg';
import AutocompleteSvg from '../../assets/icons/autocomplete.svg';
import HistorySvg from '../../assets/icons/history.svg';
import ChutakSvg from '../../assets/icons/chhutak.svg';
import FixedSvg from '../../assets/icons/fixed.svg';
import SalarySvg from '../../assets/icons/salary.svg';
import LocationSvg from '../../assets/icons/location.svg';
import CompanySvg from '../../assets/icons/company.svg';
import SkillsSvg from '../../assets/icons/skills.svg';
import InquirySvg from '../../assets/icons/inquiry.svg';
import ContactSvg from '../../assets/icons/contact.svg';
import PoolSvg from '../../assets/icons/pool.svg';
import EditSvg from '../../assets/icons/edit.svg';
import SaveSvg from '../../assets/icons/save.svg';
import CancelSvg from '../../assets/icons/cancel.svg';
import RetrySvg from '../../assets/icons/retry.svg';
import BackSvg from '../../assets/icons/back.svg';
import ErrorSvg from '../../assets/icons/error.svg';
import SuccessSvg from '../../assets/icons/success.svg';
import WarningSvg from '../../assets/icons/warning.svg';
import EmptyStateSvg from '../../assets/icons/empty_state.svg';

// ─── Required icon keys ──────────────────────────────────────────────────────

/** All valid icon key strings for the HiraRozgar app. */
export type IconKey =
  | 'home'
  | 'settings'
  | 'profile'
  | 'logout'
  | 'language'
  | 'theme'
  | 'job_seeker'
  | 'recruiter'
  | 'apply'
  | 'deactivate'
  | 'delete'
  | 'payment'
  | 'receipt'
  | 'subscription'
  | 'upi'
  | 'phone'
  | 'otp'
  | 'lock'
  | 'search'
  | 'autocomplete'
  | 'history'
  | 'chhutak'
  | 'fixed'
  | 'salary'
  | 'location'
  | 'company'
  | 'skills'
  | 'inquiry'
  | 'contact'
  | 'pool'
  | 'edit'
  | 'save'
  | 'cancel'
  | 'retry'
  | 'back'
  | 'error'
  | 'success'
  | 'warning'
  | 'empty_state';

/** All required keys as a runtime array for validation. */
const REQUIRED_KEYS: IconKey[] = [
  'home', 'settings', 'profile', 'logout', 'language', 'theme',
  'job_seeker', 'recruiter', 'apply', 'deactivate', 'delete',
  'payment', 'receipt', 'subscription', 'upi',
  'phone', 'otp', 'lock',
  'search', 'autocomplete', 'history',
  'chhutak', 'fixed', 'salary', 'location', 'company',
  'skills', 'inquiry', 'contact', 'pool',
  'edit', 'save', 'cancel', 'retry', 'back',
  'error', 'success', 'warning', 'empty_state',
];

// ─── MissingIconError ────────────────────────────────────────────────────────

/**
 * Thrown when a required icon key is absent from the bundled sprite map.
 * Caught by the app-root ErrorBoundary, which renders a startup error screen.
 */
export class MissingIconError extends Error {
  /** The icon key that could not be found. */
  readonly key: string;

  constructor(key: string) {
    super(`Missing required icon: "${key}". App cannot start.`);
    this.name = 'MissingIconError';
    this.key = key;
    // Restore prototype chain for instanceof checks in transpiled environments
    Object.setPrototypeOf(this, MissingIconError.prototype);
  }
}

// ─── Icon map ────────────────────────────────────────────────────────────────

/**
 * Maps every IconKey to its SVG React component.
 * The `as unknown as React.FC<SvgProps>` casts are required because
 * SVG file imports return a component type that is compatible with but
 * not literally typed as `React.FC<SvgProps>`.
 */
const ICON_MAP: Record<IconKey, React.FC<SvgProps>> = {
  home:         HomeSvg        as unknown as React.FC<SvgProps>,
  settings:     SettingsSvg    as unknown as React.FC<SvgProps>,
  profile:      ProfileSvg     as unknown as React.FC<SvgProps>,
  logout:       LogoutSvg      as unknown as React.FC<SvgProps>,
  language:     LanguageSvg    as unknown as React.FC<SvgProps>,
  theme:        ThemeSvg       as unknown as React.FC<SvgProps>,
  job_seeker:   JobSeekerSvg   as unknown as React.FC<SvgProps>,
  recruiter:    RecruiterSvg   as unknown as React.FC<SvgProps>,
  apply:        ApplySvg       as unknown as React.FC<SvgProps>,
  deactivate:   DeactivateSvg  as unknown as React.FC<SvgProps>,
  delete:       DeleteSvg      as unknown as React.FC<SvgProps>,
  payment:      PaymentSvg     as unknown as React.FC<SvgProps>,
  receipt:      ReceiptSvg     as unknown as React.FC<SvgProps>,
  subscription: SubscriptionSvg as unknown as React.FC<SvgProps>,
  upi:          UpiSvg         as unknown as React.FC<SvgProps>,
  phone:        PhoneSvg       as unknown as React.FC<SvgProps>,
  otp:          OtpSvg         as unknown as React.FC<SvgProps>,
  lock:         LockSvg        as unknown as React.FC<SvgProps>,
  search:       SearchSvg      as unknown as React.FC<SvgProps>,
  autocomplete: AutocompleteSvg as unknown as React.FC<SvgProps>,
  history:      HistorySvg     as unknown as React.FC<SvgProps>,
  chhutak:      ChutakSvg      as unknown as React.FC<SvgProps>,
  fixed:        FixedSvg       as unknown as React.FC<SvgProps>,
  salary:       SalarySvg      as unknown as React.FC<SvgProps>,
  location:     LocationSvg    as unknown as React.FC<SvgProps>,
  company:      CompanySvg     as unknown as React.FC<SvgProps>,
  skills:       SkillsSvg      as unknown as React.FC<SvgProps>,
  inquiry:      InquirySvg     as unknown as React.FC<SvgProps>,
  contact:      ContactSvg     as unknown as React.FC<SvgProps>,
  pool:         PoolSvg        as unknown as React.FC<SvgProps>,
  edit:         EditSvg        as unknown as React.FC<SvgProps>,
  save:         SaveSvg        as unknown as React.FC<SvgProps>,
  cancel:       CancelSvg      as unknown as React.FC<SvgProps>,
  retry:        RetrySvg       as unknown as React.FC<SvgProps>,
  back:         BackSvg        as unknown as React.FC<SvgProps>,
  error:        ErrorSvg       as unknown as React.FC<SvgProps>,
  success:      SuccessSvg     as unknown as React.FC<SvgProps>,
  warning:      WarningSvg     as unknown as React.FC<SvgProps>,
  empty_state:  EmptyStateSvg  as unknown as React.FC<SvgProps>,
};

// ─── IconRegistry singleton ──────────────────────────────────────────────────

/**
 * IconRegistry
 *
 * Singleton that owns the icon map and enforces startup validation.
 *
 * - `validate()` checks every required key against ICON_MAP;
 *   throws `MissingIconError` on first missing key.
 * - `getIcon(key)` returns the component for the given key;
 *   throws `MissingIconError` if somehow called with an absent key.
 *
 * `validate()` is called **immediately at module load time** (last line
 * of this file) so that importing this module is sufficient to trigger
 * the check — no extra call required by the consumer.
 */
export const IconRegistry = {
  /**
   * Validates that every required icon key is present in the icon map.
   * Throws `MissingIconError` with the offending key on first failure.
   * Called automatically at module load; also safe to call manually in tests.
   */
  validate(): void {
    for (const key of REQUIRED_KEYS) {
      const component = ICON_MAP[key];
      if (component == null) {
        throw new MissingIconError(key);
      }
    }
  },

  /**
   * Returns the SVG React component for the given icon key.
   * @throws {MissingIconError} if the key has no registered component.
   */
  getIcon(key: IconKey): React.FC<SvgProps> {
    const component = ICON_MAP[key];
    if (component == null) {
      throw new MissingIconError(key);
    }
    return component;
  },
};

// ─── Startup validation — runs on import ─────────────────────────────────────
// Importing this module is enough to trigger validation (Req 1.4).
IconRegistry.validate();
